version: '3'
services:
  db:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
    volumes:
      - store:/var/lib/mysql
  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0"
    environment:
      EDITOR: vim
      RAILS_ENV: development
      TZ: 'Asia/Tokyo'
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    tty: true
    stdin_open: true
volumes:
  store:
    driver: local
  bundle:
    driver: local
